ALTER TABLE users
  ADD COLUMN IF NOT EXISTS coachmarks_welcome_seen BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS coachmarks_session_seen  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS bonus_credits            INT     NOT NULL DEFAULT 0;
